name: guessing-game

services:
  frontend:
    network_mode: bridge
    container_name: guessfront
    build:
      context: frontend
    depends_on:
      - backend
    expose:
      - "3000"
    labels:
      - "tech.dnsmanager.domain=example"

  backend:
    network_mode: bridge
    container_name: guessback
    build:
      context: backend
    expose:
      - "7133"
    labels:
      - "tech.dnsmanager.domain=exampleapi"

networks:
  default:
    driver: bridge
